### ISSUE TITLE
Multiple edges on the output file.

### ISSUE THREAD

**Issue by zericardo** [zericardo/ggmModel#4]
It seems that multiple edges are being created on the output file (it is a edge list right?).  I believe the model is supposed to generate simple undirected networks.

**Comment by thmosqueiro** [comment]
Can you post an example?

**Comment by thmosqueiro** [comment]
Care to try it?

**Comment by zericardo** [comment]
I'll try it today, and then reply here if it is working correctly.

2016-01-14 2:21 GMT-02:00 Thiago Mosqueiro notifications@github.com:

> Care to try it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zericardo/ggmModel/issues/4#issuecomment-171526527.

## 

_Atenciosamente,_
_José Ricardo F. Ronqui_

**Comment by zericardo** [comment]
I tested it today and it seems the problem is solved.
